from pathlib import Path

from loadout.frontmatter import parse_rule, parse_skill_md, split_frontmatter
from loadout.headers import inject_header, loadout_metadata


def test_loadout_metadata_uses_short_sha() -> None:
    meta = loadout_metadata("rules/foo.mdc", "9f2c1ab1234567890")
    assert meta == {
        "loadout.managed": "true",
        "loadout.source": "rules/foo.mdc",
        "loadout.sha": "9f2c1ab",
    }


def test_loadout_metadata_uses_full_sha_when_shorter_than_seven() -> None:
    meta = loadout_metadata("rules/foo.mdc", "abc")
    assert meta["loadout.sha"] == "abc"


def test_inject_header_merges_metadata_into_skill_frontmatter() -> None:
    content = """---
name: db-migrations
description: Create and apply database migrations.
metadata:
  owner: platform-team
---

# Database migrations
"""
    result = inject_header(content, "skills/db-migrations/SKILL.md", "9f2c1ab1234567")

    data, body, _ = split_frontmatter(result)
    assert data["name"] == "db-migrations"
    assert data["metadata"] == {
        "owner": "platform-team",
        "loadout.managed": "true",
        "loadout.source": "skills/db-migrations/SKILL.md",
        "loadout.sha": "9f2c1ab",
    }
    assert "<!-- GENERATED by loadout" not in result
    assert body.lstrip().startswith("# Database migrations")

    parse_skill_md(
        Path("skills/db-migrations/SKILL.md"),
        result,
        dir_name="db-migrations",
    )


def test_inject_header_adds_metadata_to_rule_frontmatter() -> None:
    content = """---
description: Commit message style.
globs: ["**/*"]
alwaysApply: false
---
Body text.
"""
    result = inject_header(content, "rules/core/commit-style.mdc", "9f2c1ab")

    data, body, _ = split_frontmatter(result)
    assert data["description"] == "Commit message style."
    assert data["globs"] == ["**/*"]
    assert data["alwaysApply"] is False
    assert data["metadata"] == {
        "loadout.managed": "true",
        "loadout.source": "rules/core/commit-style.mdc",
        "loadout.sha": "9f2c1ab",
    }
    assert "<!-- GENERATED by loadout" not in result
    assert body.lstrip().startswith("Body text.")
    parse_rule(Path("rules/core/commit-style.mdc"), result)


def test_inject_header_creates_frontmatter_when_missing() -> None:
    content = "# Plain rule\n\nSome content.\n"
    result = inject_header(content, "rules/core/commit-style.mdc", "abc1234")

    data, body, _ = split_frontmatter(result)
    assert data == {
        "metadata": {
            "loadout.managed": "true",
            "loadout.source": "rules/core/commit-style.mdc",
            "loadout.sha": "abc1234",
        }
    }
    assert body.lstrip() == "# Plain rule\n\nSome content.\n"


def test_inject_header_overwrites_prior_loadout_metadata_keys() -> None:
    content = """---
name: example
description: An example skill.
metadata:
  loadout.managed: "true"
  loadout.source: skills/example/SKILL.md
  loadout.sha: oldsha1
  owner: platform-team
---

# Example
"""
    result = inject_header(content, "skills/example/SKILL.md", "newsha12")
    data, _, _ = split_frontmatter(result)
    assert data["metadata"]["loadout.sha"] == "newsha1"
    assert data["metadata"]["owner"] == "platform-team"
    assert data["metadata"]["loadout.managed"] == "true"
