from pathlib import Path

from loadout.frontmatter import parse_rule, parse_skill_md
from loadout.headers import format_header, inject_header


def test_inject_header_places_header_after_frontmatter() -> None:
    content = """---
name: db-migrations
description: Create and apply database migrations.
---

# Database migrations
"""
    result = inject_header(content, "skills/db-migrations/SKILL.md", "9f2c1ab1234567")

    assert result.startswith("---\n")
    assert result.index("---\n", 4) > 0
    header_start = result.index("<!-- GENERATED by loadout.")
    closing_fence = result.index("---\n", 4)
    assert header_start > closing_fence
    assert "source: skills/db-migrations/SKILL.md @ 9f2c1ab" in result
    assert "# Database migrations" in result

    parse_skill_md(
        Path("skills/db-migrations/SKILL.md"),
        result,
        dir_name="db-migrations",
    )


def test_inject_header_prepends_when_no_frontmatter() -> None:
    content = "# Plain rule\n\nSome content.\n"
    result = inject_header(content, "rules/core/commit-style.mdc", "abc1234")

    assert result.startswith("<!-- GENERATED by loadout.")
    assert "source: rules/core/commit-style.mdc @ abc1234" in result
    assert result.endswith("# Plain rule\n\nSome content.\n")


def test_format_header_uses_short_sha() -> None:
    assert " @ 9f2c1ab" in format_header("rules/foo.mdc", "9f2c1ab1234567890")


def test_format_header_uses_full_sha_when_shorter_than_seven() -> None:
    assert " @ abc" in format_header("rules/foo.mdc", "abc")


def test_inject_header_after_rule_frontmatter() -> None:
    content = """---
description: Commit message style.
globs: ["**/*"]
alwaysApply: false
---
Body text.
"""
    result = inject_header(content, "rules/core/commit-style.mdc", "9f2c1ab")

    parse_rule(Path("rules/core/commit-style.mdc"), result)
    assert "<!-- GENERATED by loadout." in result
    assert result.index("<!-- GENERATED") > result.index("---\n", 4)
