from __future__ import annotations

import json
import os
import shutil
from pathlib import Path
from typing import Any

import pytest

from loadout.blocks import (
    AGENT_RULES_BEGIN,
    AGENT_RULES_END,
    CLAUDE_IMPORT_BEGIN,
    CLAUDE_IMPORT_END,
)
from loadout.errors import DriftError, ValidationError
from loadout.models import load_lockfile
from loadout.sync import sync

FIXTURE = Path(__file__).parent / "fixtures" / "mini_loadout"

RULE_A = ".cursor/rules/a.mdc"
RULE_B = ".cursor/rules/b.mdc"
SKILL_MD = ".claude/skills/demo/SKILL.md"
SKILL_SCRIPT = ".claude/skills/demo/scripts/run.sh"
SKILL_REFERENCE = ".claude/skills/demo/references/runbook.md"
SKILL_ASSET = ".claude/skills/demo/assets/template.txt"
SKILL_AGENT = ".claude/skills/demo/agents/reviewer.md"
HOOK_SCRIPT = ".cursor/hooks/demo/guard.sh"
CURSOR_HOOKS = ".cursor/hooks.json"
CLAUDE_SETTINGS = ".claude/settings.json"
CURSOR_MCP = ".cursor/mcp.json"
CLAUDE_MCP = ".mcp.json"
PROJECT_AGENT = ".claude/agents/demo_agent.md"


def write_manifest(project: Path, body: str) -> None:
    project.mkdir(parents=True, exist_ok=True)
    (project / ".loadout.yaml").write_text(body)


def manifest_body(
    loadouts: str = "[python]",
    *,
    extra: str = "",
) -> str:
    return f"""source: https://example.com/loadout
ref: v1.0.0
loadouts: {loadouts}
{extra}"""


def copy_fixture(tmp_path: Path) -> Path:
    source = tmp_path / "loadout_src"
    shutil.copytree(FIXTURE, source)
    return source


@pytest.fixture
def project(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Path:
    monkeypatch.setenv("LOADOUT_PATH", str(FIXTURE))
    root = tmp_path / "project"
    write_manifest(root, manifest_body())
    return root


def read_lock(project: Path) -> dict[str, Any]:
    return json.loads((project / ".loadout.lock").read_text())


def snapshot(root: Path) -> dict[str, tuple[bytes, int]]:
    return {
        path.relative_to(root).as_posix(): (path.read_bytes(), path.stat().st_mode)
        for path in sorted(root.rglob("*"))
        if path.is_file()
    }


def test_fresh_sync_writes_rules_skills_and_lockfile(project: Path) -> None:
    result = sync(project)

    assert (project / RULE_A).is_file()
    assert (project / RULE_B).is_file()
    assert (project / SKILL_MD).is_file()
    assert (project / SKILL_SCRIPT).is_file()
    assert (project / HOOK_SCRIPT).is_file()
    assert (project / CURSOR_HOOKS).is_file()
    assert (project / CLAUDE_SETTINGS).is_file()
    assert (project / CURSOR_MCP).is_file()
    assert (project / CLAUDE_MCP).is_file()
    assert (project / PROJECT_AGENT).is_file()
    assert result.added == 13
    assert result.updated == 0
    assert result.removed == 0

    lock = read_lock(project)
    assert lock["lockfile_version"] == 1
    assert lock["resolved_sha"] == "local"
    assert [entry["dest"] for entry in lock["files"]] == sorted(
        [
            SKILL_MD,
            SKILL_SCRIPT,
            SKILL_ASSET,
            SKILL_AGENT,
            SKILL_REFERENCE,
            RULE_A,
            RULE_B,
            HOOK_SCRIPT,
            CURSOR_HOOKS,
            CLAUDE_SETTINGS,
            CURSOR_MCP,
            CLAUDE_MCP,
            PROJECT_AGENT,
        ]
    )


def test_sync_injects_header_into_rules_and_skill_md(project: Path) -> None:
    sync(project)

    rule = (project / RULE_A).read_text()
    assert "description: Core test rule" in rule
    assert "loadout.managed: 'true'" in rule or 'loadout.managed: "true"' in rule
    assert "loadout.source: rules/core/a.mdc" in rule
    assert "loadout.sha: local" in rule
    assert "<!-- GENERATED by loadout" not in rule

    skill = (project / SKILL_MD).read_text()
    assert "loadout.source:" in skill
    assert "<!-- GENERATED by loadout" not in skill


def test_sync_copies_bundled_skill_files_verbatim_and_skips_evals(project: Path) -> None:
    sync(project)

    assert (project / SKILL_SCRIPT).read_bytes() == (FIXTURE / "skills/demo/scripts/run.sh").read_bytes()
    assert (project / ".claude/skills/demo/references/runbook.md").read_bytes() == (
        FIXTURE / "skills/demo/references/runbook.md"
    ).read_bytes()
    assert (project / ".claude/skills/demo/assets/template.txt").read_bytes() == (
        FIXTURE / "skills/demo/assets/template.txt"
    ).read_bytes()
    assert (project / ".claude/skills/demo/agents/reviewer.md").read_bytes() == (
        FIXTURE / "skills/demo/agents/reviewer.md"
    ).read_bytes()
    assert not (project / ".claude/skills/demo/evals").exists()


def test_sync_preserves_binary_skill_assets(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    source = copy_fixture(tmp_path)
    binary_asset = source / "skills/demo/assets/icon.bin"
    binary_asset.write_bytes(b"\x00\xff\x10\x80demo\x00")
    monkeypatch.setenv("LOADOUT_PATH", str(source))
    project = tmp_path / "project"
    write_manifest(project, manifest_body())

    sync(project)

    assert (project / ".claude/skills/demo/assets/icon.bin").read_bytes() == (binary_asset.read_bytes())


def test_sync_preserves_executable_bit_and_records_mode(project: Path) -> None:
    sync(project)

    assert os.access(project / SKILL_SCRIPT, os.X_OK)
    modes = {entry["dest"]: entry.get("mode") for entry in read_lock(project)["files"]}
    assert modes[SKILL_SCRIPT] == "755"
    assert modes[RULE_A] is None


def test_sync_creates_no_alternate_skill_directories(project: Path) -> None:
    sync(project)

    assert not (project / ".agents").exists()
    assert not (project / ".cursor/skills").exists()


def test_second_sync_reports_no_changes_and_leaves_files_untouched(
    project: Path,
) -> None:
    sync(project)
    before = snapshot(project)

    result = sync(project)

    assert (result.added, result.updated, result.removed) == (0, 0, 0)
    assert result.unchanged == 13
    assert not result.agents_changed
    assert not result.claude_changed
    assert snapshot(project) == before


def test_removing_loadout_prunes_only_its_files(project: Path) -> None:
    sync(project)
    unrelated = project / ".cursor/rules/hand-written.mdc"
    unrelated.write_text("mine\n")

    write_manifest(project, manifest_body("[base]"))
    result = sync(project)

    assert not (project / RULE_B).exists()
    assert not (project / PROJECT_AGENT).exists()
    assert (project / RULE_A).is_file()
    assert unrelated.read_text() == "mine\n"
    assert result.removed == 2


def test_unmatched_exclude_is_a_validation_error(project: Path) -> None:
    write_manifest(project, manifest_body(extra="exclude:\n  - rules/python/gone.mdc\n"))

    with pytest.raises(ValidationError, match="gone.mdc"):
        sync(project)


def test_destination_collision_is_a_validation_error(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    source = copy_fixture(tmp_path)
    (source / "loadouts/base.yaml").write_text(
        """name: base
description: Base rules and skills
rules:
  - src: rules/core/a.mdc
    dest: .cursor/rules/shared.mdc
  - src: rules/python/b.mdc
    dest: .cursor/rules/shared.mdc
"""
    )
    monkeypatch.setenv("LOADOUT_PATH", str(source))
    project = tmp_path / "project"
    write_manifest(project, manifest_body("[base]"))

    with pytest.raises(ValidationError, match="collision"):
        sync(project)


def test_skill_name_directory_mismatch_is_a_validation_error(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    source = copy_fixture(tmp_path)
    (source / "skills/demo/SKILL.md").write_text("---\nname: not-demo\ndescription: Demo skill\n---\n\n# Demo\n")
    monkeypatch.setenv("LOADOUT_PATH", str(source))
    project = tmp_path / "project"
    write_manifest(project, manifest_body("[base]"))

    with pytest.raises(ValidationError, match="directory name"):
        sync(project)


def test_renamed_skill_destination_basename_is_a_validation_error(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    source = copy_fixture(tmp_path)
    (source / "loadouts/base.yaml").write_text(
        """name: base
description: Base rules and skills
skills:
  - src: skills/demo
    dest: infra/.claude/skills/renamed
"""
    )
    monkeypatch.setenv("LOADOUT_PATH", str(source))
    project = tmp_path / "project"
    write_manifest(project, manifest_body("[base]"))

    with pytest.raises(ValidationError, match="renamed"):
        sync(project)


def test_skills_dir_relocation_prunes_the_old_location(project: Path) -> None:
    sync(project)

    write_manifest(project, manifest_body(extra="skills_dir: .agents/skills\n"))
    result = sync(project)

    assert (project / ".agents/skills/demo/SKILL.md").is_file()
    assert not (project / ".claude/skills").exists()
    assert result.removed == 5
    assert result.added == 5


def test_agents_block_indexes_every_rule_with_scope_and_description(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    source = copy_fixture(tmp_path)
    (source / "rules/core/a.mdc").write_text("---\ndescription: Core test rule\nalwaysApply: true\n---\n\nCore rule.\n")
    (source / "rules/python/b.mdc").write_text(
        '---\ndescription: Python test rule\nglobs: ["**/*.py"]\n---\n\nPython rule.\n'
    )
    (source / "loadouts/python.yaml").write_text(
        """name: python
extends: [base]
description: Python-specific rules
rules:
  - src: rules/python/b.mdc
    dest: packages/api/.cursor/rules/b.mdc
"""
    )
    monkeypatch.setenv("LOADOUT_PATH", str(source))
    project = tmp_path / "project"
    write_manifest(project, manifest_body())

    result = sync(project)

    agents = (project / "AGENTS.md").read_text()
    assert result.agents_changed
    assert "| `.cursor/rules/a.mdc` | Always | Core test rule |" in agents
    assert "| `packages/api/.cursor/rules/b.mdc` | `**/*.py` | Python test rule |" in agents


def test_rule_without_globs_or_always_apply_renders_on_request(project: Path) -> None:
    sync(project)

    assert "| `.cursor/rules/a.mdc` | On request | Core test rule |" in (project / "AGENTS.md").read_text()


def test_hand_written_agents_content_survives_resync(project: Path) -> None:
    (project / "AGENTS.md").write_text(
        f"# House rules\n\nAbove the block.\n\n{AGENT_RULES_BEGIN}\nstale\n{AGENT_RULES_END}\n\nBelow the block.\n"
    )

    sync(project)
    agents = (project / "AGENTS.md").read_text()

    assert agents.startswith("# House rules\n\nAbove the block.\n")
    assert agents.endswith("Below the block.\n")
    assert "stale" not in agents

    sync(project)
    assert (project / "AGENTS.md").read_text() == agents


def test_agents_block_is_removed_when_no_rules_remain(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    source = copy_fixture(tmp_path)
    (source / "loadouts/base.yaml").write_text(
        """name: base
description: Base rules and skills
skills:
  - src: skills/demo
"""
    )
    monkeypatch.setenv("LOADOUT_PATH", str(source))
    project = tmp_path / "project"
    write_manifest(project, manifest_body("[base]"))
    (project / "AGENTS.md").write_text(f"# House rules\n\n{AGENT_RULES_BEGIN}\nstale table\n{AGENT_RULES_END}\n")

    sync(project)

    agents = (project / "AGENTS.md").read_text()
    assert AGENT_RULES_BEGIN not in agents
    assert "# House rules" in agents
    assert [block["file"] for block in read_lock(project)["managed_blocks"]] == ["CLAUDE.md"]


def test_mangled_agents_block_aborts_without_overwriting(project: Path) -> None:
    mangled = f"# House rules\n\n{AGENT_RULES_BEGIN}\nhalf a block\n"
    (project / "AGENTS.md").write_text(mangled)

    with pytest.raises(ValidationError, match="exactly one"):
        sync(project)

    assert (project / "AGENTS.md").read_text() == mangled
    assert not (project / ".loadout.lock").exists()
    assert not (project / RULE_A).exists()


def test_claude_bridge_writes_import_block_above_existing_content(
    project: Path,
) -> None:
    (project / "CLAUDE.md").write_text("# Claude notes\n\nKeep me.\n")

    result = sync(project)

    claude = (project / "CLAUDE.md").read_text()
    assert result.claude_changed
    assert claude.startswith(f"{CLAUDE_IMPORT_BEGIN}\n@AGENTS.md\n{CLAUDE_IMPORT_END}")
    assert claude.endswith("# Claude notes\n\nKeep me.\n")


def test_claude_bridge_creates_missing_file(project: Path) -> None:
    sync(project)

    assert (project / "CLAUDE.md").read_text() == (f"{CLAUDE_IMPORT_BEGIN}\n@AGENTS.md\n{CLAUDE_IMPORT_END}\n")


def test_claude_bridge_false_skips_claude_md(project: Path) -> None:
    write_manifest(project, manifest_body(extra="claude_bridge: false\n"))

    result = sync(project)

    assert not (project / "CLAUDE.md").exists()
    assert not result.claude_changed
    assert [block["file"] for block in read_lock(project)["managed_blocks"]] == ["AGENTS.md"]


def test_claude_bridge_disabled_removes_a_previously_written_import_block(
    project: Path,
) -> None:
    (project / "CLAUDE.md").write_text("# Claude notes\n\nKeep me.\n")
    sync(project)
    assert CLAUDE_IMPORT_BEGIN in (project / "CLAUDE.md").read_text()

    write_manifest(project, manifest_body(extra="claude_bridge: false\n"))
    result = sync(project)

    claude = (project / "CLAUDE.md").read_text()
    assert CLAUDE_IMPORT_BEGIN not in claude
    assert CLAUDE_IMPORT_END not in claude
    assert claude.endswith("# Claude notes\n\nKeep me.\n")
    assert result.claude_changed
    assert [block["file"] for block in read_lock(project)["managed_blocks"]] == ["AGENTS.md"]

    sync(project, check=True)


def test_disabling_claude_bridge_without_resyncing_is_drift(project: Path) -> None:
    sync(project)
    write_manifest(project, manifest_body(extra="claude_bridge: false\n"))

    with pytest.raises(DriftError, match="CLAUDE.md"):
        sync(project, check=True)


def test_claude_bridge_disabled_leaves_an_untouched_claude_md_alone(
    project: Path,
) -> None:
    write_manifest(project, manifest_body(extra="claude_bridge: false\n"))
    (project / "CLAUDE.md").write_text("# Claude notes\n\nKeep me.\n")

    result = sync(project)

    assert (project / "CLAUDE.md").read_text() == "# Claude notes\n\nKeep me.\n"
    assert not result.claude_changed


def test_dest_escaping_the_project_is_a_validation_error(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    source = copy_fixture(tmp_path)
    (source / "loadouts/base.yaml").write_text(
        """name: base
description: Base rules and skills
rules:
  - src: rules/core/a.mdc
    dest: ../evil/a.mdc
"""
    )
    monkeypatch.setenv("LOADOUT_PATH", str(source))
    project = tmp_path / "project"
    write_manifest(project, manifest_body("[base]"))

    with pytest.raises(ValidationError, match="outside the project"):
        sync(project)

    assert not (tmp_path / "evil").exists()


def test_prune_ignores_lockfile_entries_pointing_outside_the_project(
    project: Path,
) -> None:
    sync(project)
    outside = project.parent / "outside.txt"
    outside.write_text("keep me\n")
    lock_path = project / ".loadout.lock"
    lock_path.write_text(lock_path.read_text().replace(RULE_A, "../outside.txt"))

    result = sync(project)

    assert outside.read_text() == "keep me\n"
    assert result.removed == 0


def test_missing_skill_directory_is_a_validation_error(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    source = copy_fixture(tmp_path)
    (source / "loadouts/base.yaml").write_text(
        """name: base
description: Base rules and skills
skills:
  - src: skills/gone
"""
    )
    monkeypatch.setenv("LOADOUT_PATH", str(source))
    project = tmp_path / "project"
    write_manifest(project, manifest_body("[base]"))

    with pytest.raises(ValidationError, match="skills/gone"):
        sync(project)

    assert not (project / ".loadout.lock").exists()


def test_malformed_manifest_is_a_validation_error(project: Path) -> None:
    write_manifest(project, "source: https://example.com/loadout\nloadouts: [\n")

    with pytest.raises(ValidationError, match="invalid YAML"):
        sync(project)


def test_malformed_lockfile_is_a_validation_error(project: Path) -> None:
    sync(project)
    (project / ".loadout.lock").write_text('{"lockfile_version": 1,\n')

    with pytest.raises(ValidationError, match="invalid JSON"):
        sync(project)


def test_sync_prints_summary(project: Path, capsys: pytest.CaptureFixture[str]) -> None:
    sync(project)

    out = capsys.readouterr().out
    assert "13 added" in out
    assert "AGENTS.md" in out
    assert "Cursor" in out


def test_check_passes_on_a_clean_tree(project: Path) -> None:
    sync(project)

    result = sync(project, check=True)

    assert (result.added, result.updated, result.removed) == (0, 0, 0)


def test_check_writes_nothing(project: Path) -> None:
    with pytest.raises(DriftError):
        sync(project, check=True)

    assert not (project / ".loadout.lock").exists()
    assert not (project / RULE_A).exists()
    assert not (project / "AGENTS.md").exists()


def test_check_without_lockfile_is_drift(project: Path) -> None:
    with pytest.raises(DriftError, match="lockfile"):
        sync(project, check=True)


def test_hand_edited_rule_is_drift(project: Path) -> None:
    sync(project)
    (project / RULE_A).write_text("hand edited\n")

    with pytest.raises(DriftError, match=RULE_A):
        sync(project, check=True)


def test_hand_edited_skill_script_is_drift(project: Path) -> None:
    sync(project)
    (project / SKILL_SCRIPT).write_text("#!/bin/sh\nrm -rf /\n")

    with pytest.raises(DriftError, match="run.sh"):
        sync(project, check=True)


def test_deleted_generated_file_is_drift(project: Path) -> None:
    sync(project)
    (project / RULE_B).unlink()

    with pytest.raises(DriftError, match="missing"):
        sync(project, check=True)


def test_bumped_ref_without_sync_is_drift(project: Path) -> None:
    sync(project)
    write_manifest(
        project,
        manifest_body().replace("ref: v1.0.0", "ref: v2.0.0"),
    )

    with pytest.raises(DriftError, match="ref"):
        sync(project, check=True)


def test_stale_agents_block_is_drift(project: Path) -> None:
    sync(project)
    agents = (project / "AGENTS.md").read_text()
    (project / "AGENTS.md").write_text(agents.replace("Core test rule", "Something else entirely"))

    with pytest.raises(DriftError, match="AGENTS.md"):
        sync(project, check=True)


def test_check_ignores_content_outside_the_block_markers(project: Path) -> None:
    sync(project)
    agents = (project / "AGENTS.md").read_text()
    (project / "AGENTS.md").write_text(f"{agents}\nA new hand-written section.\n")

    sync(project, check=True)


def test_check_warns_instead_of_failing_on_local_sha_mismatch(
    project: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    sync(project)
    lock_path = project / ".loadout.lock"
    lock_path.write_text(lock_path.read_text().replace('"resolved_sha": "local"', '"resolved_sha": "9f2c1ab"'))
    capsys.readouterr()

    sync(project, check=True)

    assert "warning" in capsys.readouterr().out.lower()


def test_lockfile_records_a_hash_for_every_copied_file(project: Path) -> None:
    sync(project)

    lock = load_lockfile(project / ".loadout.lock")
    assert lock is not None
    assert {entry.dest for entry in lock.files} == {
        RULE_A,
        RULE_B,
        SKILL_MD,
        SKILL_SCRIPT,
        SKILL_REFERENCE,
        SKILL_ASSET,
        SKILL_AGENT,
        HOOK_SCRIPT,
        CURSOR_HOOKS,
        CLAUDE_SETTINGS,
        CURSOR_MCP,
        CLAUDE_MCP,
        PROJECT_AGENT,
    }
    assert all(len(entry.sha256) == 64 for entry in lock.files)


def test_real_feature_loadouts_scope_rules_and_terraform_skill(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    repository = Path(__file__).parent.parent
    monkeypatch.setenv("LOADOUT_PATH", str(repository))
    project = tmp_path / "project"
    write_manifest(project, manifest_body("[aws, terraform, playwright-e2e]"))

    sync(project)

    assert (project / "infra/.cursor/rules/aws-conventions.mdc").is_file()
    assert (project / "infra/.claude/skills/terraform-plan-review/SKILL.md").is_file()
    assert (project / "e2e/.cursor/rules/e2e-conventions.mdc").is_file()
    assert (project / ".claude/agents/davinci.md").is_file()
    assert (project / ".claude/agents/review_orchestrator.md").is_file()
    assert (project / ".claude/agents/review_correctness.md").is_file()
    assert (project / ".claude/agents/e2e_test_generator.md").is_file()
    assert (project / ".cursor/hooks/deny-dangerous/deny-dangerous.sh").is_file()
    assert (project / ".cursor/hooks.json").is_file()
    assert (project / ".claude/settings.json").is_file()
    assert (project / ".cursor/mcp.json").is_file()
    cursor_mcp = (project / ".cursor/mcp.json").read_text()
    assert "aws-knowledge" in cursor_mcp
    assert "knowledge-mcp.global.api.aws" in cursor_mcp
    assert not (project / ".cursor/rules/aws-conventions.mdc").exists()
    assert not (project / ".cursor/rules/e2e-conventions.mdc").exists()
    assert not (project / "tests/e2e").exists()


def test_real_non_terraform_loadouts_do_not_vendor_terraform_content(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    repository = Path(__file__).parent.parent
    monkeypatch.setenv("LOADOUT_PATH", str(repository))
    project = tmp_path / "project"
    write_manifest(project, manifest_body("[base, python-monorepo, playwright-e2e]"))

    sync(project)

    paths = [path.relative_to(project).as_posix() for path in project.rglob("*")]
    assert paths, "sync wrote nothing, so this test would pass vacuously"
    assert (project / ".claude/agents/python_coder.md").is_file()
    assert (project / ".claude/agents/davinci.md").is_file()
    assert (project / ".claude/agents/review_security.md").is_file()
    assert (project / ".claude/agents/e2e_test_generator.md").is_file()
    assert not (project / "infra").exists()
    assert not any("terraform" in path.lower() for path in paths)
    assert not any("aws-conventions" in path for path in paths)
    assert "terraform" not in (project / "AGENTS.md").read_text().lower()
    assert not any("terraform-plan-review" in text or "aws-conventions" in text for text in _project_text(project))


def test_real_agents_loadout_writes_langchain_docs_mcp(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    repository = Path(__file__).parent.parent
    monkeypatch.setenv("LOADOUT_PATH", str(repository))
    project = tmp_path / "project"
    write_manifest(project, manifest_body("[agents]"))

    sync(project)

    cursor = json.loads((project / ".cursor/mcp.json").read_text())
    assert cursor["mcpServers"]["langchain-docs"]["url"] == "https://docs.langchain.com/mcp"
    claude = json.loads((project / ".mcp.json").read_text())
    assert claude["mcpServers"]["langchain-docs"] == {
        "type": "http",
        "url": "https://docs.langchain.com/mcp",
    }
    assert (project / ".claude/agents/davinci.md").is_file()
    assert (project / ".claude/agents/review_orchestrator.md").is_file()
    assert (project / ".claude/skills/refining-evals/SKILL.md").is_file()
    assert (project / ".cursor/rules/agent-authoring.mdc").is_file()
    assert not (project / ".claude/agents/_agent_template.md").exists()


def _project_text(project: Path) -> list[str]:
    """Every file sync produced, so vendored content is checked, not just path names."""
    return [
        path.read_text(errors="ignore")
        for path in project.rglob("*")
        if path.is_file() and path.name != ".loadout.yaml"
    ]
