from __future__ import annotations

HEADER_TEMPLATE = """<!-- GENERATED by loadout. Do not edit.
     source: {src} @ {short_sha}
     edit upstream, then run `just loadout-update` -->"""


def _short_sha(sha: str) -> str:
    return sha if len(sha) <= 7 else sha[:7]


def format_header(src: str, sha: str) -> str:
    return HEADER_TEMPLATE.format(src=src, short_sha=_short_sha(sha))


def _find_frontmatter_end(content: str) -> int | None:
    if not content.startswith("---"):
        return None

    lines = content.splitlines(keepends=True)
    if not lines or lines[0].rstrip("\r\n") != "---":
        return None

    for index, line in enumerate(lines[1:], start=1):
        if line.rstrip("\r\n") == "---":
            return sum(len(part) for part in lines[: index + 1])

    return None


def inject_header(content: str, src: str, sha: str) -> str:
    header = format_header(src, sha)
    end = _find_frontmatter_end(content)
    if end is not None:
        before = content[:end]
        after = content[end:]
        if after.startswith("\r\n"):
            return before + "\r\n" + header + after
        if after.startswith("\n"):
            return before + "\n" + header + after
        return before + "\n" + header + "\n" + after

    if content:
        return header + "\n\n" + content
    return header + "\n"
